```{r tidy=FALSE}
margin_X = c(0.2, 0.1, 0.7 )
cond_Y_X = matrix(
   c( 0.5, 0.0, 3/7,
      0.5, 1.0, 0.0,
      0.0, 0.0, 4/7),
   byrow=TRUE,
   nrow=3)

single_draw = function() {
   x = sample(c(1,2,3), size=1, prob=margin_X)
   y = sample(c(1,2,3), size=1, prob=cond_Y_X[,x])
   return(c(x,y))
}

nsim=10000
df = data.frame(
   t(replicate(nsim, single_draw()))
)
colnames(df) = c("x","y")
t(table(df))

```


The variables `margin_X` and `cond_X_Y` are what you get when you compute the marginal and the conditional distribution from the given joint-distribution table as you did in your probability class. 

The function `single_draw` performs a single draw form the distribution of $(X,Y)$ by first drawing the value of $X$ from its marginal distribution. Then, it chooses the row of the conditional distribution table according to the obtained value of $X$ and simulates from it. 

The function `replicate` is used to repeat `single_draw` many times and collect the results. By default, `replicate` attaches the output of each new "replication" as a new column and not a row, so we need to transpose the final product. That is what the function `t()` is for. We turn the result into a data frame because the function `table` knows how to handle data frames automatically. Another use of the transpose gives `x` the horizontal axis, and `y` the vertical one, like in the statement of the problem. 
