1. Simulate $n=1000$ draws from the  distribution whose distribution table is given by
```{r echo=FALSE}
library(kableExtra)
df = t(
    data.frame(x = c(0.2,0.3,0.1,0.4) )
    )
colnames(df) = c("2","4","8","16")
kable(df, row.names=FALSE) %>% 
   kable_styling(full_width=FALSE)

```

   Draw a histogram of your results.

2.  You may have learned in probability how to compute the pdf $f_Y(y)$ of a
    transformation $Y=g(X)$ of a random variable with pdf $f_X(x)$. Suppose
    that you forgot how to do that, but have access to $10,000$ simulations from
    the distribution of $X$. How would you get an approximate idea about the
    shape of the function $f_Y$?
    
       More concretely, take $X$ to be exponentially distributed with parameter $1$ and
       $g(x) = \sin(x)$ and produce a picture that approximates the pdf $f_Y$ of $Y$.
       (Note: even if you remember how to do this analytically, you will run into a
       difficulty. The function $\sin(x)$ is not one-to-one and the method usually
       taught in probability classes will not apply. If you learned how to do it in the
       many-to-one case of $g(x)= \sin(x)$, kudos to your instructor!)

3.  Let $X$ be a random variable with the Cauchy distribution, and $Y =
    \operatorname{arctan}(X)$. R allows you to simulate from the Cauchy
    distribution, even if you do not know what it is. How would you use that to
    make an educated guess as to what the distribution of $Y$ is? To make your
    life easier, consider $\tfrac{2}{\pi} Y$ first. 


