Let $(Z,W)$ is be a discrete random vector with the following joint distribution table (different rows correspond to different values of $Z$):

```{r echo=FALSE}
probs = c(0.2,0.1,0.0,0.1,0.2,0.1,0.0,0.1,0.2);
df = data.frame(matrix(probs, nrow=3, byrow=TRUE))
colnames(df) = c("-1","0","1")
rownames(df) = c("-1","0","1")
kable(df, 
      # striped=TRUE, 
      row.names=TRUE) %>% 
kableExtra::column_spec(1, bold = T) %>%
kableExtra::kable_styling(full_width=FALSE)
```

and set $$ X = Z+W \text{ and } Y=Z W.$$

1. Find the distribution table for $(X,Y)$ and compute $\EE[ X Y]$ and $\PP[X=0 | Y=0]$ analytically (no simulations!).
You can do this part on a separate piece of paper or inside your Rmd file if you know LaTeX. 

2. Draw $10000$ simulations of $(X,Y)$ (don't print them out). Display the
contingency table of your simulations using relative frequencies, as well as the
table of errors (differences between your contingency table and the table of
probabilities).

3. Compute $\EE[X Y]$ again, but this time using your simulations from 1. above.

4. Draw simulations from the conditional distribution of $X$, given $Y=0$. Use them to estimate the conditional probability $\PP[ X=0 | Y=0]$. 
By how much does it differ from your analytical result from 1. above. 

